/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.odeoteknologi.sdk;

import com.github.odeoteknologi.sdk.exception.InvalidStatusCodeException;
import com.github.odeoteknologi.sdk.schema.OauthRequest;
import com.github.odeoteknologi.sdk.schema.OauthResponse;
import org.apache.http.HttpResponse;
import org.apache.http.ParseException;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.BasicResponseHandler;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;

public class OdeoApi {

    protected String clientId;
    protected String clientSecret;
    protected String signingKey;
    protected String accessToken;
    protected String baseUrl;
    protected CloseableHttpClient httpClient = HttpClients.createDefault();
    protected OauthRequest oauth;
    protected JSONObject json;
    protected JSONParser parser = new JSONParser();
    protected MessageDigest digest;

    public OdeoApi() {
        this.oauth = new OauthRequest("", "");
    }

    public void setApiCredentials(String clientId, String clientSecret, String signingKey) {
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.signingKey = signingKey;

        this.oauth.setCredentials(clientId, clientSecret, "");
    }

    public void setProductionEnvironment() {
        this.baseUrl = "https://api.v2.odeo.co.id";
    }

    public void setStagingEnvironment() {
        this.baseUrl = "http://api.v2.staging.odeo.co.id";
    }

    protected long getUnixTimestamp() {
        return System.currentTimeMillis() / 1000;
    }

    public String generateBodyHash(String requestBody) {
        try {
            this.digest = MessageDigest.getInstance("SHA-256");
            byte[] rawHash  = this.digest.digest(requestBody.getBytes());
            return Base64.getEncoder().encodeToString(rawHash);
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }

        return "";
    }

    protected String generateSignature(String httpMethod, String path, String query, String timestamp, String requestBody) throws NoSuchAlgorithmException, InvalidKeyException {
        String bodyHash = this.generateBodyHash(requestBody);
        String stringToSign = String.join(":", new String[] {httpMethod.toUpperCase(), path, query, this.accessToken, String.valueOf(timestamp), bodyHash});

        Mac mac = Mac.getInstance("HmacSHA256");
        SecretKeySpec secretKey = new SecretKeySpec(this.signingKey.getBytes(), "HmacSHA256");
        mac.init(secretKey);

        return Base64.getEncoder().encodeToString(mac.doFinal(stringToSign.getBytes()));
    }

    public JSONObject createApiRequest(String method, String path, String requestBody, boolean withHeader) throws Exception {
        switch (method) {
            case "GET":
                return this.executeApiGet(path, requestBody);
            case "POST":
                return this.executeApiPost(path, requestBody, withHeader);
        }

        return null;
    }

    public OauthResponse requestAccessToken() throws Exception {
        this.json = this.createApiRequest("POST", "/oauth2/token", this.oauth.getJsonString(), false);
        OauthResponse response = new OauthResponse(this.json);
        this.accessToken = response.getAccessToken();
        return response;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    private JSONObject executeApiPost(String path, String requestBody, boolean withHeader) throws Exception {
        HttpPost request = new HttpPost(this.baseUrl + path);

        if (withHeader) {
            this.setRequestHeaders(request, "POST", path, requestBody);
        }

        StringEntity params = new StringEntity(requestBody);
        request.setEntity(params);
        HttpResponse response = httpClient.execute(request);
        this.checkResponseStatusCode(response);
        return this.parseResponseAsJSON(response);
    }

    private JSONObject executeApiGet(String path, String requestBody) throws Exception {
        HttpGet request = new HttpGet(this.baseUrl + path);
        this.setRequestHeaders(request, "GET", path, requestBody);
        HttpResponse response = httpClient.execute(request);
        this.checkResponseStatusCode(response);
        return this.parseResponseAsJSON(response);
    }

    private void setRequestHeaders(HttpGet request, String method, String path, String requestBody) throws InvalidKeyException, NoSuchAlgorithmException {
        String timestamp = String.valueOf(this.getUnixTimestamp());
        String signature = this.generateSignature(method, path, "", timestamp, requestBody);

        request.addHeader("Authorization", "Bearer " + this.accessToken);
        request.addHeader("X-Odeo-Timestamp", String.valueOf(this.getUnixTimestamp()));
        request.addHeader("X-Odeo-Signature", signature);
    }

    private void setRequestHeaders(HttpPost request, String method, String path, String requestBody) throws InvalidKeyException, NoSuchAlgorithmException {
        String timestamp = String.valueOf(this.getUnixTimestamp());
        String signature = this.generateSignature(method, path, "", timestamp, requestBody);

        request.addHeader("Authorization", "Bearer " + this.accessToken);
        request.addHeader("X-Odeo-Timestamp", String.valueOf(this.getUnixTimestamp()));
        request.addHeader("X-Odeo-Signature", signature);
    }

    private JSONObject parseResponseAsJSON(HttpResponse response) throws IOException, ParseException, org.json.simple.parser.ParseException {
        String responseString = new BasicResponseHandler().handleResponse(response);
        return (JSONObject) this.parser.parse(responseString);
    }

    private void checkResponseStatusCode(HttpResponse response) throws InvalidStatusCodeException, IOException {
        if (response.getStatusLine().getStatusCode() == 200) {
            return;
        }
        String responseString = new BasicResponseHandler().handleResponse(response);
        throw new InvalidStatusCodeException("Error: " + responseString);
    }
}
